import {notFound} from 'next/navigation';
import Link from 'next/link';
import {clientGuides} from '@/data/client-guides';
import {contact,siteUrl} from '@/data/projects';
import {pageMetadata,personId} from '@/lib/metadata';
import {Footer} from '@/components/Footer';
import GuideWorkbench from '@/components/GuideWorkbench';
type Props={params:Promise<{slug:string}>};
export const dynamicParams=false;
export function generateStaticParams(){return clientGuides.map(g=>({slug:g.slug}))}
export async function generateMetadata({params}:Props){const{slug}=await params;const g=clientGuides.find(g=>g.slug===slug);return g?pageMetadata({title:g.title,description:g.description,path:`/for-business/${slug}`,locale:'ru_RU'}):{}}
export default async function Page({params}:Props){const{slug}=await params;const g=clientGuides.find(g=>g.slug===slug);if(!g)notFound();return <main id="main" tabIndex={-1} lang="ru"><article className="journal-shell article-shell guide-shell"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:g.title,description:g.description,inLanguage:'ru',author:{'@id':personId},image:`${siteUrl}/og.png`,mainEntityOfPage:`${siteUrl}/for-business/${slug}`}).replace(/</g,'\u003c')}}/><nav className="journal-breadcrumbs" aria-label="Хлебные крошки"><Link href="/">Главная</Link><span>/</span><Link href="/guides">Материалы</Link></nav><header className="journal-heading"><span className="eyebrow">ДЛЯ ЗАКАЗЧИКА / ПРАКТИЧЕСКИЙ РАЗБОР</span><h1>{g.title}</h1><p className="guide-direct-answer">{g.intro}</p><div className="guide-byline"><Link href="/about">Владислав Иманаков</Link><Link href="/guides/editorial-policy">Редакционный подход</Link></div></header><figure className="guide-visual"><figcaption><strong>От наблюдения — к проверке</strong><span>Учебные ситуации. Они помогают выбрать следующий шаг, а не ставят диагноз вашему сайту автоматически.</span></figcaption><div className="guide-table-scroll"><table><thead><tr>{g.example[0].map(v=><th key={v} scope="col">{v}</th>)}</tr></thead><tbody>{g.example.slice(1).map((row,i)=><tr key={i}>{row.map(v=><td key={v}>{v}</td>)}</tr>)}</tbody></table></div></figure><div className="article-prose">{g.sections.map(s=><section key={s.title}><h2>{s.title}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}</div><GuideWorkbench slug={slug} tool={{kind:'checklist',title:'Зафиксируйте результат проверки',intro:'Отмечайте только проверенные пункты. В наблюдениях запишите конкретный пример или вопрос подрядчику; список можно скачать.',items:g.checks}}/><section className="guide-cta"><span className="eyebrow">НУЖНА ПОМОЩЬ С САЙТОМ?</span><h2>Разберёмся, что стоит сделать первым.</h2><p>Аудит, отдельные доработки или новый сайт — начнём с подходящего объёма.</p><a href={contact.telegram} target="_blank" rel="noreferrer">Обсудить сайт в Telegram ↗</a></section><section className="article-sources"><h2>Источник и границы рекомендаций</h2><p>Это практический порядок проверки, а не гарантия роста продаж или сохранения позиций.</p><a href={g.source.url} target="_blank" rel="noreferrer">{g.source.title} ↗</a></section><section className="article-related"><h2>Работа в портфолио</h2><Link href={`/work/${g.caseSlug}`}>{g.caseName} ↗</Link><h2>Следующий вопрос</h2>{clientGuides.filter(x=>x.slug!==slug).map(x=><Link key={x.slug} href={`/for-business/${x.slug}`}>{x.title} ↗</Link>)}</section></article><Footer/></main>}
