import Link from 'next/link';
import {contact} from '@/data/projects';
import {clientGuides} from '@/data/client-guides';
const offers=[
 {name:'Разобраться',subtitle:'Аудит существующего сайта',text:'Когда сайт уже есть, но непонятно, что мешает ему работать лучше.',items:['Разбор структуры и пути к обращению','Проверка технических ошибок и индексации','Приоритетный план: что исправить и зачем'],result:'На выходе — конкретные замечания и порядок работ.'},
 {name:'Исправить',subtitle:'Доработка без полной пересборки',text:'Когда проблема понятна и нужны изменения, которые можно проверить.',items:['Мобильная версия и ключевые сценарии','Техническое SEO и исправление страниц','Настройка событий и проверка обращений'],result:'На выходе — внедрённые изменения и проверка результата.'},
 {name:'Создать',subtitle:'Новый сайт или редизайн',text:'Когда нужна новая структура, подача услуг и техническая основа.',items:['Структура и дизайн под задачи бизнеса','Разработка и адаптация под устройства','Подготовка к поиску, аналитика и запуск'],result:'На выходе — работающий сайт с передачей доступов.'},
];
export function ClientOffers(){return <section id="services" className="client-offers" lang="ru" aria-labelledby="offers-title"><div className="client-offers-heading"><span className="eyebrow">ДЛЯ ВАШЕГО БИЗНЕСА</span><h2 id="offers-title">От проблемы<br/>к работающему сайту.</h2><p>Подключусь на нужном этапе: от разбора существующего сайта до разработки и запуска.</p></div><div className="client-offer-grid">{offers.map((o,i)=><article key={o.name}><span className="eyebrow">0{i+1} / {o.subtitle}</span><h3>{o.name}</h3><p>{o.text}</p><ul>{o.items.map(x=><li key={x}>{x}</li>)}</ul><p className="offer-result">{o.result}</p><a className="text-link" href={contact.telegram} target="_blank" rel="noreferrer">Обсудить {i===0?'аудит':i===1?'доработку':'проект'} ↗</a></article>)}</div><p className="offer-scope">Объём, стоимость и сроки согласуем до начала работ.</p><div className="client-reading"><div><span className="eyebrow">ПЕРЕД НАЧАЛОМ РАБОТЫ</span><h3>Разобраться<br/>без лишних терминов.</h3></div><div>{clientGuides.map(g=><Link key={g.slug} href={`/for-business/${g.slug}`}>{g.title}<span aria-hidden="true">↗</span></Link>)}</div></div></section>}
