'use client';
import {useState} from 'react';
import {guidePractice} from '@/data/guide-practice';
import {GuideCtaBuilder} from './GuideCtaBuilder';
import {contact} from '@/data/projects';
export function GuidePractice({slug}:{slug:string}){
 const p=guidePractice[slug];const [fields,setFields]=useState({url:'',observation:'',change:'',verification:''});const [status,setStatus]=useState('');
 if(!p)return null;
 const filled=Object.values(fields).filter(x=>x.trim()).length;
 async function copy(){try{await navigator.clipboard.writeText(output);setStatus('План скопирован — можно вставить в сообщение.');}catch{setStatus('Не удалось скопировать. Скачайте план или выделите текст ниже.');}}
 const output=`${p.task}\nСтраница / сценарий: ${fields.url||'не указан'}\nНаблюдение: ${fields.observation||'не записано'}\nИзменение: ${fields.change||'не выбрано'}\nПовторная проверка: ${fields.verification||'не описана'}\nКритерий: ${p.acceptance}`;
 function save(){const url=URL.createObjectURL(new Blob([output],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`${slug}-plan.txt`;a.click();URL.revokeObjectURL(url);setStatus('План скачан.');}
return <section className="guide-practice" aria-labelledby={`practice-${slug}`}><header><span className="eyebrow">ПРИМЕНИТЕ К СВОЕМУ САЙТУ</span><h3 id={`practice-${slug}`}>{p.task}</h3></header>{slug==='useful-website-buttons'&&<GuideCtaBuilder/>}<ol>{p.steps.map(s=><li key={s}>{s}</li>)}</ol><details><summary>Посмотреть пример наблюдения</summary><p>{p.example}</p><small>Учебная ситуация, не результат вашего сайта.</small></details><div className="workbench-fields">{([['url','Страница или сценарий'],['observation','Что произошло при проверке'],['change','Что предлагаете изменить'],['verification','Как повторно проверите результат']] as const).map(([key,label])=><label key={key}>{label}<textarea maxLength={1200} value={fields[key]} onChange={e=>setFields(v=>({...v,[key]:e.target.value}))}/></label>)}</div><p><strong>Условие готовности:</strong> {p.acceptance}</p><div className="practice-plan"><span className="eyebrow">ВАШ ПЛАН / {filled} ИЗ 4 ПОЛЕЙ</span><pre>{output}</pre></div><div className="workbench-save"><button onClick={copy} disabled={!filled}>Скопировать для сообщения</button><button onClick={save} disabled={!filled}>Скачать план проверки</button><button onClick={()=>{setFields({url:'',observation:'',change:'',verification:''});setStatus('Поля очищены.');}}>Очистить</button><span role="status">{status}</span></div><p className="workbench-note">Записи не отправляются на сервер и исчезнут после перезагрузки. Скачайте план, чтобы сохранить работу. Это ручная проверка, без автоматического сканирования сайта.</p><div className="practice-contact"><a href={contact.telegram} target="_blank" rel="noreferrer">{/form|password|order/.test(slug)?'Обсудить исправление формы':/navigation|structure|prototype/.test(slug)?'Обсудить структуру сайта':'Обсудить эту задачу на моём сайте'} ↗</a><p>Можно приложить заполненный план к сообщению в Telegram. Отправку выполняете вы.</p></div></section>;
}
