import {clientGuides} from '@/data/client-guides';
import {guideTools} from '@/data/guide-tools';
import Link from 'next/link';
import {Footer} from './Footer';
import {GUIDE_PAGE_SIZE,guideTopics,publishedGuides} from '@/lib/guides';
export function GuidesIndex({topic,page=1}:{topic?:string;page?:number}){
 const all=publishedGuides().filter(g=>!topic||g.topic===topic);const pages=Math.ceil(all.length/GUIDE_PAGE_SIZE);const base=topic?`/guides/topic/${topic}`:'/guides';
 return <main id="main" tabIndex={-1} lang="ru"><div className="journal-shell"><nav className="journal-breadcrumbs" aria-label="Хлебные крошки"><Link href="/">Главная</Link><span>/</span><Link href="/guides">Практика</Link></nav><header className="journal-heading"><span className="eyebrow">DESIGN / FIELD NOTES</span><h1>{topic?guideTopics[topic]:'Интерфейсы, которые помогают действовать.'}</h1><p>Разборы решений: от понятной ошибки в форме до структуры сайта. С примерами, ограничениями и проверками, которые можно повторить.</p></header>{!topic&&page===1&&<section className="client-guide-entry"><h2>Для заказчиков: сайт как рабочий инструмент</h2>{clientGuides.map(g=><Link key={g.slug} href={`/for-business/${g.slug}`}>{g.title} ↗</Link>)}</section>}<nav className="journal-topics" aria-label="Темы"><Link href="/guides" aria-current={!topic?'page':undefined}>Все материалы</Link>{Object.entries(guideTopics).filter(([key])=>publishedGuides().some(g=>g.topic===key)).map(([key,label])=><Link key={key} href={`/guides/topic/${key}`} aria-current={topic===key?'page':undefined}>{label}</Link>)}</nav><div className="journal-list">{all.slice((page-1)*GUIDE_PAGE_SIZE,page*GUIDE_PAGE_SIZE).map(g=><article key={g.slug}><span className="eyebrow">{guideTopics[g.topic]}</span><h2><Link href={g.canonical}>{g.h1}<span aria-hidden="true">↗</span></Link></h2><p>{g.description}</p>{guideTools[g.slug]&&<span className="guide-tool-label">Внутри: {guideTools[g.slug].title.toLocaleLowerCase('ru')}</span>}</article>)}</div><nav className="journal-pagination" aria-label="Страницы">{Array.from({length:pages},(_,i)=><Link key={i} href={i===0?base:`${base}/page/${i+1}`} aria-current={page===i+1?'page':undefined}>{i+1}</Link>)}</nav><Link href="/guides/editorial-policy">Как подготовлены материалы</Link></div><Footer/></main>;
}
