import Link from 'next/link';
import {contact} from '@/data/projects';

const services=[
 ['Комплексный аудит','Проверяю техническое состояние, структуру, контент, скорость и пользовательские сценарии. Собираю проблемы в понятный план: что исправить сейчас, что сделать следующим.','Результат: аудит с приоритетами и планом исправлений.'],
 ['Семантическое ядро','Собираю запросы через Яндекс Wordstat, очищаю и группирую по смыслу и намерению пользователя. Распределяю кластеры по страницам, нахожу темы для новых посадочных.','Результат: семантика, кластеры и карта страниц.'],
 ['Индексация и работоспособность','Проверяю ответы сервера, редиректы, битые ссылки, robots.txt, sitemap и canonical. Сверяю доступность страниц для поиска через Search Console и Яндекс Вебмастер, проверяю формы и ключевые действия.','Результат: список ошибок, исправления и повторная проверка.'],
 ['Внешние площадки','Подбираю подходящие каталоги, карты и отраслевые площадки. Создаю и оформляю карточки компании, привожу контакты и ссылки к единому виду. Подтверждение владельца — с вашим участием.','Результат: оформленные профили и реестр размещений.'],
 ['Аналитика и измерение','Подключаю или проверяю Метрику, цели и события. Разделяю источники трафика, визиты и обращения, чтобы оценивать изменения по данным.','Результат: проверенные события и понятная точка отсчёта.'],
 ['Персональные данные / РКН','Проверяю формы, согласия, политику обработки данных, сторонние сервисы и сведения об операторе. Выявляю потенциальные риски нарушений и исправляю техническую часть сайта; правовые вопросы выношу на согласование с юристом.','Результат: карта рисков и устранение найденных технических проблем.'],
];
const tools=[['google','G','Google'],['wordstat','▥','Wordstat'],['yandex','Я','Яндекс'],['metrika','▥','Метрика'],['gsc','⌕','Search Console'],['frog','frog','Screaming Frog'],['rkn','shield','РКН']];
export function SeoServices(){return <section id="seo" className="seo-services" aria-labelledby="seo-services-title">
 <header className="seo-services-top"><span>DESIGN IS THE START.</span><span>SEARCH / STRUCTURE / PERFORMANCE</span></header>
 <div className="seo-services-layout"><div className="seo-services-intro"><h2 id="seo-services-title">Beyond design.<br/>Into search.</h2><div className="seo-services-word" aria-hidden="true">SEO<span>↗</span></div><p lang="ru">Делаю сайт понятным для людей.<br/>И доступным для поиска.</p><ul className="seo-tool-list" aria-label="Инструменты и направления работы">{tools.map(([id,mark,name])=><li key={id}><span className={`seo-tool-icon tool-${id}`} aria-hidden="true">{mark==='frog'?<svg viewBox="0 0 40 40"><circle cx="12" cy="12" r="7"/><circle cx="28" cy="12" r="7"/><ellipse cx="20" cy="25" rx="17" ry="12"/><circle className="frog-eye" cx="12" cy="11" r="2"/><circle className="frog-eye" cx="28" cy="11" r="2"/><path d="M12 26 Q20 33 28 26"/></svg>:mark==='shield'?<svg viewBox="0 0 40 40"><path d="M20 3 34 9v12c0 9-14 16-14 16S6 30 6 21V9Z"/><path d="m13 20 5 5 10-11"/></svg>:mark}</span><span>{name}</span></li>)}</ul></div>
 <div className="seo-service-list" lang="ru"><p className="seo-service-lead">От первого аудита<br/>до внедрения исправлений.</p>{services.map(([title,body,result],i)=><details key={title} open={i===0}><summary><span className="seo-service-index">0{i+1}</span><h3>{title}</h3><span className="seo-service-plus" aria-hidden="true">+</span></summary><div className="seo-service-detail"><p>{body}</p><p>{result}</p>{i===5&&<a href="https://pd.rkn.gov.ru/" target="_blank" rel="noreferrer">Портал персональных данных РКН ↗</a>}</div></details>)}</div></div>
 <footer className="seo-services-bottom"><a href={`mailto:${contact.email}?subject=${encodeURIComponent('SEO-аудит сайта')}`} lang="ru">Обсудить аудит сайта <span aria-hidden="true">↗</span></a><Link href="/work/allnrg"><span>IN PRACTICE / ALLIANCE ENERGY</span><strong>169 organic search visits ↗</strong></Link></footer>
 </section>;}
