import { writeFile } from 'node:fs/promises';
import { readJSON,writeJSON,requestYandex } from './api.mjs';
const command=process.argv[2]||'normalize';
export const normalize=query=>query.toLowerCase().replace(/ё/g,'е').replace(/onboarding/g,'онбординг').replace(/dashboard/g,'дашборд').replace(/user flow/g,'юзер флоу').replace(/ui\/ux|ux\/ui/g,'ux ui').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
const intent=q=>/(?:^|\s)(или|vs|versus)(?:\s|$)|сравнен|разница/u.test(q)?'comparison':/чек ?лист|чеклист/u.test(q)?'checklist':/пример|образец/u.test(q)?'examples':/почему|ошибк|не работает|проблем|броса|отказ/u.test(q)?'problem-solving':/как |созда|настро|сделать|провер/u.test(q)?'how-to':/заказать|стоимость|цена услуг/u.test(q)?'commercial':/лучши|выбрать/u.test(q)?'commercial-investigation':'informational';
const facets=[['mobile',/мобильн|телефон|смартфон/],['figma',/figma|фигм/],['a11y',/доступност|клавиатур|скринридер|wcag/],['validation',/валидац|ошибк|неверн/],['password',/парол/],['ecommerce',/интернет магазин|товар|корзин/],['b2b',/b2b|crm|saas/],['metrics',/метрик|конверси|аналитик|показател/],['process',/этап|процесс|провести|провер|аудит/],['patterns',/виды|паттерн|тип |типы/],['design',/дизайн|ux| ui |интерфейс/]];
const noise=/госуслуг|налог|росреестр|миграц|пропис|заявлен|бланк|\bр1\d|паспорт|загран|граждан|фмс|ндфл|егэ|огэ|снилс|инн |размер обув|wildberries|вайлдбер|озон|ozon|вконтакте|яндекс маркет|на авито|windows|виндов|телеграм|телевизор|принтер|steam|minecraft|роблокс|курсы|ваканси|зарплат|реферат|диплом|диссертац|скачать|торрент|готовые ответы|python|javascript|jquery|php|sql|laravel|django|bootstrap|html|css/;
const semanticAnchor=/дизайн|ux|ui|интерфейс|сайт|интернет магазин|приложен|пользовател|юзабилити|figma|фигм|онбординг|прототип|чек ?лист|дашборд|пагинац|скелетон|карта пути|юзер флоу|валидац|пустые состоян/;
const ambiguousNoise=/образовани.*форм|форм.*слов|прилагательн|существительн|глагол|граммат|морфолог|геометр|официальный сайт|форма ошибки$|доступност.*провер|провер.*доступност|ping|пинг|мониторинг доступност|\bhttp|1с|1 с |эксель|excel|power bi/;
const topicNoise=(q,t)=>({forms:/образован|укажите|числительн|падеж|выберите|форм[аы] слов|исправьте ошибки в форме|отметь.*ошиб|отметьте.*ошиб/,filters:/купить|маслян|маслян|масля|воздушн|топлив|воды|фильтров|фильтра для/,empty:/голов|душ|внутри|бойлер/,cart:/мусор/,motion:/мод |майнкрафт/,responsive:/одежд|конкурс/,tables:/электронн|9 класс|редактировани|типы интерфейс/}[t]?.test(q)||false);
if(command==='normalize'){
 const collection=await readJSON('seo/data/collection.json',[]);const map=new Map();let raw=0;
 for(const seed of collection)for(const [kind,rows]of [['top',seed.record.data.results||[]],['association',seed.record.data.associations||[]]])for(const row of rows){
  raw++;const normalizedQuery=normalize(row.phrase);const existing=map.get(normalizedQuery);const evidence={seed:seed.query,kind,count:Number(row.count),retrievedAt:seed.record.retrievedAt};
  if(existing){existing.frequency=Math.max(existing.frequency,Number(row.count));existing.evidence.push(evidence);continue;}
  const relevant=!noise.test(normalizedQuery)&&!ambiguousNoise.test(normalizedQuery)&&!topicNoise(normalizedQuery,seed.topic)&&(kind==='top')&&(semanticAnchor.test(normalizedQuery)||['forms','empty','contrast','keyboard','loading','tooltip','tabs'].includes(seed.topic));
  map.set(normalizedQuery,{query:row.phrase,normalizedQuery,frequency:Number(row.count),region:'225',source:'wordstat',intent:intent(normalizedQuery),topic:seed.topic,clusterId:'',serpChecked:false,status:relevant?'candidate':'rejected',rejectionReason:relevant?null:'Out-of-scope, ambiguous product intent, implementation-only or unrelated association',evidence:[evidence]});
 }
 const keywords=[...map.values()];await writeFile('seo/data/keywords.jsonl',keywords.map(k=>JSON.stringify(k)).join('\n')+'\n');await writeJSON('seo/reports/normalization.json',{raw,normalized:keywords.length,candidates:keywords.filter(k=>k.status==='candidate').length,notes:['Frequencies are overlapping broad match phrase counts, never unique demand totals.','Conservative lexical and concept synonym normalization; original queries and evidence preserved.']});console.log(await readJSON('seo/reports/normalization.json'));
}
if(command==='cluster'){
 const {readFile}=await import('node:fs/promises');const keywords=(await readFile('seo/data/keywords.jsonl','utf8')).trim().split('\n').filter(Boolean).map(JSON.parse);const groups=new Map();
 for(const k of keywords.filter(k=>k.status==='candidate')){
  const facet=facets.find(([,pattern])=>pattern.test(k.normalizedQuery))?.[0]||'general';
  const key=`${k.topic}-${k.intent}-${facet}`;k.clusterId=key;
  if(!groups.has(key))groups.set(key,[]);groups.get(key).push(k);
 }
 const clusters=[...groups].map(([clusterId,rows])=>{rows.sort((a,b)=>b.frequency-a.frequency);return{clusterId,primaryKeyword:rows[0].query,secondaryKeywords:rows.slice(1).map(k=>k.query),totalVolume:rows.reduce((n,k)=>n+k.frequency,0),demandFloor:Math.max(...rows.map(k=>k.frequency)),volumeMeaning:'overlapping broad-match phrase sum; not additive audience',intent:rows[0].intent,topic:rows[0].topic,serpCompetitors:[],serpOverlap:null,existingCompetingPage:null,recommendedUrl:`/guides/${clusterId}`,status:'candidate',keywordCount:rows.length,semanticMethod:'topic+intent+concept facets with explicit synonym normalization; SERP overlap refines finalists'}});
 await writeJSON('seo/data/clusters.json',clusters);await writeFile('seo/data/keywords.jsonl',keywords.map(k=>JSON.stringify(k)).join('\n')+'\n');console.log(`clusters: ${clusters.length}`);
}
if(command==='score'){
 const clusters=await readJSON('seo/data/clusters.json',[]),serps=await readJSON('seo/data/serp-assessments.json',[]);
 const opportunities=clusters.map(c=>{const serp=serps.findLast(s=>s.clusterId===c.clusterId&&s.query===c.primaryKeyword);const rawFeatures={demand:Math.min(20,Math.log10(1+c.demandFloor)*5),intentClarity:c.intent==='informational'?9:15,expertiseRelevance:15,commercialProximity:['conversion','redesign','ux','checkout','forms','signup'].includes(c.topic)?12:8,uniqueValuePotential:['forms','accessibility','navigation','empty','errors','motion','filters','dashboard','prototyping'].includes(c.topic)?15:10,caseRelevance:['redesign','ux','usability','navigation','responsive','conversion','prototyping'].includes(c.topic)?8:3,serpOpportunity:serp?Math.min(10,4+serp.editorialCount):0,duplicatePenalty:c.keywordCount===1?0:2,doorwayPenalty:0,thinRiskPenalty:c.demandFloor<10?10:0,cannibalizationPenalty:serp?.mergeInto?25:0};const score=Math.round(rawFeatures.demand+rawFeatures.intentClarity+rawFeatures.expertiseRelevance+rawFeatures.commercialProximity+rawFeatures.uniqueValuePotential+rawFeatures.caseRelevance+rawFeatures.serpOpportunity-rawFeatures.duplicatePenalty-rawFeatures.doorwayPenalty-rawFeatures.thinRiskPenalty-rawFeatures.cannibalizationPenalty);return{...c,score,rawFeatures,serpChecked:!!serp,serpAssessment:serp||null,status:serp?.mergeInto?'merge':score>=70?'strong':score>=55?'review':'rejected',reason:serp?'Demand, distinct-intent heuristics and cached SERP screen; editorial decision still required':'Preliminary only: demand and topic fit; SERP unverified'};}).sort((a,b)=>b.score-a.score||b.demandFloor-a.demandFloor);
 await writeJSON('seo/data/opportunities.json',opportunities);await writeJSON('seo/reports/opportunities.json',opportunities.slice(0,100));console.log({opportunities:opportunities.length,strong:opportunities.filter(o=>o.status==='strong').length});
}
if(command==='serp'){
 const opportunities=await readJSON('seo/data/opportunities.json',[]);const selected=opportunities.filter(o=>o.status!=='rejected').slice(0,130);const assessed=await readJSON('seo/data/serp-assessments.json',[]);const force=process.argv.includes('--force-refresh');
 const clean=text=>text.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();
 for(const candidate of selected){
  if(assessed.some(s=>s.clusterId===candidate.clusterId&&s.query===candidate.primaryKeyword)&&!force)continue;
  try{const record=await requestYandex('serp',{query:{searchType:'SEARCH_TYPE_RU',queryText:candidate.primaryKeyword,page:'0'},region:'225',responseFormat:'FORMAT_XML',groupSpec:{groupMode:'GROUP_MODE_FLAT',groupsOnPage:'10',docsInGroup:'1'}},{force});const xml=Buffer.from(record.data.rawData||'','base64').toString('utf8');
   if(/<error\b/.test(xml))throw new Error('SERP returned an API-level error; raw response retained');
   const documents=[...xml.matchAll(/<doc\b[^>]*>([\s\S]*?)<\/doc>/g)].map(([,doc])=>({url:clean(/<url>([\s\S]*?)<\/url>/.exec(doc)?.[1]||''),title:clean(/<title>([\s\S]*?)<\/title>/.exec(doc)?.[1]||''),snippet:clean(/<passages>([\s\S]*?)<\/passages>/.exec(doc)?.[1]||'')})).filter(d=>d.url);
   const editorialCount=documents.filter(d=>/как|почему|гайд|руководств|ошиб|пример|чек|дизайн|ux/i.test(d.title)).length;
   const row={clusterId:candidate.clusterId,query:candidate.primaryKeyword,checkedAt:record.retrievedAt,documents,editorialCount,dominantIntent:editorialCount>=5?'editorial/mixed':'mixed/manual-review',assessmentLimit:'SERP titles/snippets establish expectations only; H1/depth require sampled page inspection, snippets not factual sources',mergeInto:null,serpOverlap:0};
   for(const prior of assessed.filter(p=>p.clusterId!==candidate.clusterId&&p.documents?.length&&opportunities.find(o=>o.clusterId===p.clusterId&&o.primaryKeyword===p.query)?.topic===candidate.topic)){const urls=new Set(prior.documents.map(d=>d.url));const overlap=documents.filter(d=>urls.has(d.url)).length/Math.max(1,Math.min(documents.length,prior.documents.length));if(overlap>row.serpOverlap){row.serpOverlap=overlap;if(overlap>=.6)row.mergeInto=prior.clusterId;}}
   assessed.push(row);await writeJSON('seo/data/serp-assessments.json',assessed);console.log(`SERP ${assessed.length}/${selected.length}: ${candidate.clusterId} (${documents.length})`);
  }catch(error){console.error(error.message);process.exitCode=1;break;}
 }
 await writeJSON('seo/reports/serp-state.json',{selected:selected.length,completed:assessed.length,complete:selected.every(c=>assessed.some(a=>a.clusterId===c.clusterId&&a.query===c.primaryKeyword)),updatedAt:new Date().toISOString()});
}
