import { mkdir, writeFile } from 'node:fs/promises';
import { articleProblems, getArticles } from '../../lib/editorial.ts';

const all = getArticles();
const published = all.filter(a=>a.status==='indexable');
const errors = [], warnings = [], similarities = [];
const normalize = text=>text.toLowerCase().replace(/ё/g,'е').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const seen = { title:new Map(), description:new Map(), h1:new Map(), intentKey:new Map() };
const stop=new Set('и в во на по для с со из у к не это как что или а о об от до при если то но его ее их уже также чтобы можно который'.split(' '));
const termCounts = text=>normalize(text).split(' ').filter(t=>t.length>2&&!stop.has(t)).reduce((map,t)=>map.set(t,(map.get(t)||0)+1),new Map());
const docs=published.map(a=>({slug:a.slug,terms:termCounts(a.body)}));
const df=new Map();for(const doc of docs)for(const t of doc.terms.keys())df.set(t,(df.get(t)||0)+1);
for(const doc of docs){doc.vector=new Map([...doc.terms].map(([t,n])=>[t,(1+Math.log(n))*Math.log(1+docs.length/df.get(t))]));doc.norm=Math.hypot(...doc.vector.values());}
for(let i=0;i<docs.length;i++)for(let j=i+1;j<docs.length;j++){
  let dot=0;for(const [term,weight]of docs[i].vector)dot+=weight*(docs[j].vector.get(term)||0);
  const score=dot/(docs[i].norm*docs[j].norm||1);
  if(score>.45)similarities.push({a:docs[i].slug,b:docs[j].slug,cosine:Number(score.toFixed(3)),kind:'lexical-screening-not-semantic-verdict'});
  if(score>.9)errors.push(`${docs[i].slug}/${docs[j].slug}: very high text similarity; merge or independent review required`);
  else if(score>.7)warnings.push(`${docs[i].slug}/${docs[j].slug}: review semantic overlap`);
}
const slugSet=new Set(published.map(a=>a.slug));
const staticPaths=new Set(['/','/about','/play','/journal','/feed.xml','/work/allnrg','/work/legacy-rheumatology','/work/vpn-equipment','/work/pdp','/work/khasaut-tour','/work/aurelia-atelier']);
for(const a of all){
  for(const problem of articleProblems(a))errors.push(`${a.slug}: ${problem}`);
  if(a.status!=='indexable')continue;
  for(const field of Object.keys(seen)){const value=normalize(a[field]);if(seen[field].has(value))errors.push(`${a.slug}: duplicate ${field} with ${seen[field].get(value)}`);seen[field].set(value,a.slug);}
  for(const slug of a.related)if(!slugSet.has(slug)||slug===a.slug)errors.push(`${a.slug}: invalid related article ${slug}`);
  const links=[...a.body.matchAll(/\[[^\]]+\]\(([^\s)]+)\)/g)].map(match=>match[1]);
  if(!links.some(url=>url.startsWith('/journal/')))errors.push(`${a.slug}: missing contextual in-text article link`);
  for(const url of links){
    if(url.startsWith('/')){const path=url.split(/[?#]/)[0];if(!staticPaths.has(path)&&!slugSet.has(path.replace(/^\/journal\//,'')))errors.push(`${a.slug}: broken internal link ${path}`);}
    else if(!url.startsWith('https://')&&!url.startsWith('#'))errors.push(`${a.slug}: unsupported link scheme`);
  }
  if(!a.sources.every(source=>links.includes(source.url)))warnings.push(`${a.slug}: some sources listed only in source appendix`);
}
const report={generatedAt:new Date().toISOString(),counts:{total:all.length,indexable:published.length,draft:all.filter(a=>a.status==='draft').length,reviewed:all.filter(a=>a.status==='reviewed').length},errors,warnings,similarities,notes:['Every indexable article is linked from its paginated journal and topic hub.','Canonical and structured data are generated by the server template; browser QA validates rendered output.','Cosine similarity is a duplicate-candidate screen. Independent SEO reviewer must assess intent and semantic overlap.','External source reachability is checked during source research, not guessed from URL syntax.']};
await mkdir('data/seo/reports',{recursive:true});
await writeFile('data/seo/reports/latest.json',JSON.stringify(report,null,2));
console.log(JSON.stringify({counts:report.counts,errors,warnings,similarityPairs:similarities.length},null,2));
if(errors.length)process.exitCode=1;
